databases:
  - name: authenticateme
    user: authenticateme
    plan: free
    region: ohio

services:
  - type: web
    name: authenticateme
    plan: free
    region: ohio
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: authenticateme
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false